CUSTOM_FIELDS = {
	"Shift Assignment": [
		{
			"fieldname": "custom_shift_assignment_location_section",
			"fieldtype": "Section Break",
			"label": "Shift Assignment Location",
			"insert_after": "amended_from",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_shift_assignment_location",
			"label": "Shift Assignment Location",
			"fieldtype": "Table",
			"options": "Shift Assignment Location",
			"insert_after": "custom_shift_assignment_location_section",
			"allow_on_submit": 1,
			"system_generated": 0,
		},
	],
	"Additional Salary": [
		{
			"fieldname": "custom_date_of_joining",
			"label": "Date Of Joining",
			"fieldtype": "Date",
			"insert_after": "department",
			"fetch_from": "employee.date_of_joining",
			"read_only": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_annual_gross_earning",
			"label": "Annual Gross Earning",
			"fieldtype": "Currency",
			"insert_after": "custom_date_of_joining",
			"read_only": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_ctc",
			"label": "Total Cost To Company (CTC)",
			"fieldtype": "Currency",
			"insert_after": "custom_annual_gross_earning",
			"read_only": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_duration_of_additional_salary",
			"label": "Duration Of Additional Salary",
			"fieldtype": "Select",
			"options": "\nQuarterly\nHalf Yearly\nYearly",
			"insert_after": "is_recurring",
			"depends_on": "eval:doc.is_recurring",
			"mandatory_depends_on": "eval:doc.is_recurring",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_additional_salary_payment_history_section_break",
			"fieldtype": "Section Break",
			"insert_after": "ref_docname",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_additional_salary_payment_history",
			"label": "Additional Salary Payment History",
			"fieldtype": "Table",
			"options": "Additional Salary Payment History",
			"insert_after": "custom_additional_salary_payment_history_section_break",
			"read_only": 1,
			"allow_on_submit": 1,
			"system_generated": 0,
		},
	],
	"Employee": [
		{
			"fieldname": "custom_aadhaar_number",
			"label": "Aadhaar Number",
			"fieldtype": "Data",
			"insert_after": "provident_fund_account",
			"reqd": 1,
			"length": 12,
			"default": "",
			"unique": 1,
			"system_generated": 0,
		}
	],
	"Attendance": [
		{
			"fieldname": "custom_penalty",
			"label": "Penalty",
			"fieldtype": "Check",
			"insert_after": "early_exit",
			"read_only": 1,
			"allow_on_submit": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_half_day_type",
			"label": "Half Day Type",
			"fieldtype": "Select",
			"insert_after": "total_leave_days",
			"options": "First Half\nSecond Half",
			"depends_on": "eval:doc.half_day",
			"mandatory_depends_on": "eval:doc.half_day",
			"system_generated": 0,
		},
	],
	"Attendance Request": [
		{
			"fieldname": "custom_half_day_type",
			"label": "Half Day Type",
			"fieldtype": "Select",
			"insert_after": "half_day_date",
			"options": "First Half\nSecond Half",
			"depends_on": "eval:doc.half_day",
			"mandatory_depends_on": "eval:doc.half_day",
			"system_generated": 0,
		}
	],
	"Leave Application": [
		{
			"fieldname": "custom_half_day_type",
			"label": "Half Day Type",
			"fieldtype": "Select",
			"insert_after": "total_leave_days",
			"options": "First Half\nSecond Half",
			"depends_on": "eval:doc.half_day",
			"mandatory_depends_on": "eval:doc.half_day",
			"system_generated": 0,
		}
	],
}
