CUSTOM_FIELDS = {
	"Shift Assignment": [
		{
			"fieldname": "custom_shift_assignment_location_section",
			"fieldtype": "Section Break",
			"label": "Shift Assignment Location",
			"insert_after": "amended_from",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_shift_assignment_location",
			"label": "Shift Assignment Location",
			"fieldtype": "Table",
			"options": "Shift Assignment Location",
			"insert_after": "custom_shift_assignment_location_section",
			"allow_on_submit": 1,
			"system_generated": 0,
		},
	],
	# ------ Expense Claim Type ------
	"Expense Claim Type": [
		{
			"fieldname": "custom_expense_limit_details",
			"label": "Expense Limit Details",
			"fieldtype": "Table",
			"options": "Expense Limit Details",
			"insert_after": "description",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_expenses_requirement_section",
			"label": "Expense Requirements",
			"fieldtype": "Section Break",
			"insert_after": "custom_expense_limit_details",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_is_attachment_required",
			"label": "Is Attachment Required",
			"fieldtype": "Check",
			"insert_after": "custom_expenses_requirement_section",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_is_request_form_required",
			"label": "Is Request Form Required",
			"fieldtype": "Check",
			"insert_after": "custom_is_attachment_required",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_is_accommodation_required",
			"label": "Is Accommodation Required",
			"fieldtype": "Check",
			"insert_after": "custom_is_request_form_required",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_expense_limit_details",
			"label": "Expense Limit Details",
			"fieldtype": "Table",
			"options": "Expense Limit Details",
			"insert_after": "description",
			"system_generated": 0,
		},
	],
	#  ------ Employee Advance ------
	"Employee Advance": [
		{
			"fieldname": "custom_employee_advance_approval_hiestory_section",
			"fieldtype": "Section Break",
			"insert_after": "amended_from",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_employee_advance_approval_hiestory",
			"label": "Employee Advance Approval History",
			"fieldtype": "Table",
			"options": "Workflow Action Log",
			"insert_after": "custom_employee_advance_approval_hiestory_section",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_approval_reject_reason",
			"label": "Approval Reject Reason",
			"fieldtype": "Small Text",
			"insert_after": "custom_employee_advance_approval_hiestory",
			"allow_on_submit": 1,
			"no_copy": 1,
			"system_generated": 0,
			"hidden": 1,
		},
	],
	# ------ Expense Claim ------
	"Expense Claim": [
		{
			"fieldname": "custom_expense_claim_approval_hiestory_section",
			"fieldtype": "Section Break",
			"insert_after": "total_amount_reimbursed",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_expense_claim_approval_hiestory",
			"label": "Expense Claim Approval History",
			"fieldtype": "Table",
			"options": "Workflow Action Log",
			"insert_after": "custom_expense_claim_approval_hiestory_section",
			"allow_on_submit": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_approval_reject_reason",
			"label": "Approval Reject Reason",
			"fieldtype": "Small Text",
			"insert_after": "custom_expense_claim_approval_hiestory",
			"allow_on_submit": 1,
			"system_generated": 0,
			"hidden": 1,
		},
	],
	#  Expense Claim Detail Child table in Expense Claim
	"Expense Claim Detail": [
		{
			"fieldname": "custom_expense",
			"label": "Expense",
			"fieldtype": "Link",
			"options": "Expense",
			"insert_after": "expense_date",
			"in_list_view": 1,
			"columns": 2,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_is_overlimit__expense",
			"label": "Is Overlimit Expense",
			"fieldtype": "Check",
			"insert_after": "custom_expense",
			"fetch_from": "custom_expense.is_overlimit__expense",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_is_request_form_required",
			"label": "Is Request Form Required",
			"fieldtype": "Check",
			"insert_after": "custom_expense",
			"fetch_from": "custom_expense.is_request_form_required",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_request_form",
			"label": "Request Form",
			"fieldtype": "Link",
			"options": "Travel Request",
			"insert_after": "custom_is_request_form_required",
			"depends_on": "eval:doc.custom_is_request_form_required == 1",
			"mandatory_depends_on": "eval:doc.custom_is_request_form_required == 1",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_expense_details_section",
			"fieldtype": "Section Break",
			"insert_after": "description",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_city",
			"label": "City",
			"fieldtype": "Link",
			"options": "City",
			"insert_after": "custom_expense_details_section",
			"fetch_from": "custom_expense.city",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_limit_amount",
			"label": "Limit Amount",
			"fieldtype": "Currency",
			"insert_after": "custom_city",
			"fetch_from": "custom_expense.limit_amount",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_travel_info_section",
			"label": "Travel Info",
			"fieldtype": "Section Break",
			"insert_after": "custom_limit_amount",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_from_city",
			"label": "From City",
			"fieldtype": "Link",
			"options": "City",
			"insert_after": "custom_travel_info_section",
			"fetch_from": "custom_expense.from_city",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_total_distance_in_km",
			"label": "Total Distance (in KM)",
			"fieldtype": "Float",
			"insert_after": "custom_from_city",
			"fetch_from": "custom_expense.total_distance_in_km",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_travel_info_column_break",
			"fieldtype": "Column Break",
			"insert_after": "custom_total_distance_in_km",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_to_city",
			"label": "To City",
			"fieldtype": "Link",
			"options": "City",
			"insert_after": "custom_travel_info_column_break",
			"fetch_from": "custom_expense.to_city",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_per_km_rate",
			"label": "Per KM Rate",
			"fieldtype": "Currency",
			"insert_after": "custom_to_city",
			"fetch_from": "custom_expense.per_km_rate",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
	],
	# Employee
	"Employee": [
		{
			"fieldname": "custom_expense_claim_overlimit_limit_tab",
			"label": "Over-limit Approval",
			"fieldtype": "Tab Break",
			"insert_after": "grade",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_expense_overlimit_authorization",
			"label": "Expense Over-limit Authorization",
			"fieldtype": "Table",
			"options": "Expense Over-limit Authorization",
			"insert_after": "custom_expense_claim_overlimit_limit_tab",
			"system_generated": 0,
		},
	],
	# Employee Grade
	"Employee Grade": [
		{
			"fieldname": "custom_grade_description",
			"label": "Grade Description",
			"fieldtype": "Small Text",
			"insert_after": "default_salary_structure",
			"reqd": 1,
			"system_generated": 0,
		}
	],
	#  Travel Request
	"Travel Request": [
		{
			"fieldname": "custom_requested_date",
			"label": "Requested Date",
			"fieldtype": "Date",
			"insert_after": "travel_type",
			"reqd": 1,
			"default": "Today",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_employee_grade",
			"label": "Employee Grade",
			"fieldtype": "Link",
			"options": "Employee Grade",
			"insert_after": "employee_name",
			"fetch_from": "employee.grade",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_employee_designation",
			"label": "Employee Designation",
			"fieldtype": "Link",
			"options": "Designation",
			"insert_after": "date_of_birth",
			"fetch_from": "employee.designation",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_employee_department",
			"label": "Employee Department",
			"fieldtype": "Link",
			"options": "Department",
			"insert_after": "custom_employee_designation",
			"fetch_from": "employee.department",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_total_costing_section",
			"label": "Total Costing",
			"fieldtype": "Section Break",
			"insert_after": "costings",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_total_estimated_cost",
			"label": "Total Estimated Cost",
			"fieldtype": "Currency",
			"insert_after": "custom_total_costing_section",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_total_advance_required",
			"label": "Total Advance Required",
			"fieldtype": "Currency",
			"insert_after": "custom_total_costing_section",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_total_advance_approved",
			"label": "Total Advance Approved",
			"fieldtype": "Currency",
			"insert_after": "custom_total_advance_required",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_travel_request_approval_hiestory_section",
			"fieldtype": "Section Break",
			"insert_after": "amended_from",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_remark",
			"label": "Reason of Approve/Reject Travel Request",
			"fieldtype": "Small Text",
			"insert_after": "custom_travel_request_approval_hiestory_section",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_travel_request_approval_hiestory",
			"label": "Travel Request Approval History",
			"fieldtype": "Table",
			"options": "Workflow Action Log",
			"insert_after": "custom_remark",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
	],
	# Travel Request Costing Child table in Travel Request
	"Travel Request Costing": [
		{
			"fieldname": "custom_is_accommodation_required",
			"fieldtype": "Check",
			"label": "Is Accommodation Required",
			"insert_after": "expense_type",
			"fetch_from": "expense_type.custom_is_accommodation_required",
			"read_only": 1,
			"no_copy": 1,
			"system_generated": 0,
		},
		{
			"fieldname": "custom_no_of_nights",
			"label": "Number of Nights",
			"fieldtype": "Int",
			"insert_after": "custom_is_accommodation_required",
			"depends_on": "eval:doc.custom_is_accommodation_required",
			"mandatory_depends_on": "eval:doc.custom_is_accommodation_required",
			"system_generated": 0,
		},
		{
			"fieldname": "custom_no_of_days",
			"label": "Number of Days",
			"fieldtype": "Int",
			"insert_after": "custom_no_of_nights",
			"depends_on": "eval:doc.custom_is_accommodation_required",
			"mandatory_depends_on": "eval:doc.custom_is_accommodation_required",
			"system_generated": 0,
		},
	],
}
