def get_property_setters():
	return [
		# Shift Assignment
		{
			"doctype": "Shift Assignment",
			"doctype_or_field": "DocField",
			"fieldname": "shift_location",
			"property": "hidden",
			"property_type": "Check",
			"value": 1,
		},
		#  Additional Salary
		{
			"doctype": "Additional Salary",
			"doctype_or_field": "DocField",
			"fieldname": "to_date",
			"property": "mandatory_depends_on",
			"property_type": "Data",
			"value": "",
		},
		{
			"doctype": "Additional Salary",
			"doctype_or_field": "DocField",
			"fieldname": "from_date",
			"property": "mandatory_depends_on",
			"property_type": "Data",
			"value": "",
		},
		{
			"doctype": "Additional Salary",
			"doctype_or_field": "DocField",
			"fieldname": "to_date",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": 1,
		},
		{
			"doctype": "Additional Salary",
			"doctype_or_field": "DocField",
			"fieldname": "amount",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": 1,
		},
		# Employee
		{
			"doctype": "Employee",
			"doctype_or_field": "DocField",
			"fieldname": "prefered_contact_email",
			"property": "default",
			"property_type": "Text",
			"value": "Company Email",
		},
		{
			"doctype": "Employee",
			"doctype_or_field": "DocField",
			"fieldname": "salary_mode",
			"property": "default",
			"property_type": "Text",
			"value": "Bank",
		},
		{
			"doctype": "Employee",
			"doctype_or_field": "DocField",
			"fieldname": "person_to_be_contacted",
			"property": "reqd",
			"property_type": "Check",
			"value": 1,
		},
		{
			"doctype": "Employee",
			"doctype_or_field": "DocField",
			"fieldname": "emergency_phone_number",
			"property": "reqd",
			"property_type": "Check",
			"value": 1,
		},
		{
			"doctype": "Employee",
			"doctype_or_field": "DocField",
			"fieldname": "relation",
			"property": "reqd",
			"property_type": "Check",
			"value": 1,
		},
		{
			"doctype": "Employee",
			"doctype_or_field": "DocField",
			"fieldname": "salary_mode",
			"property": "reqd",
			"property_type": "Check",
			"value": 1,
		},
	]
